# Generated by Django 3.1.2 on 2020-10-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('artista', '0003_auto_20201019_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='categoria',
            field=models.ForeignKey(help_text='Escolha apenas uma categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.categoria'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cpf',
            field=models.CharField(help_text='Apenas números', max_length=255),
        ),
    ]
