# Generated by Django 3.1.2 on 2020-12-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0004_auto_20201021_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
